import time

def congratulations():
    print("░█████╗░░█████╗░███╗░░██╗░██████╗░██████╗░░█████╗░████████╗██╗░░░██╗██╗░░░░░░█████╗░████████╗██╗░█████╗░███╗░░██╗░██████╗")
    print("██╔══██╗██╔══██╗████╗░██║██╔════╝░██╔══██╗██╔══██╗╚══██╔══╝██║░░░██║██║░░░░░██╔══██╗╚══██╔══╝██║██╔══██╗████╗░██║██╔════╝")
    print("██║░░╚═╝██║░░██║██╔██╗██║██║░░██╗░██████╔╝███████║░░░██║░░░██║░░░██║██║░░░░░███████║░░░██║░░░██║██║░░██║██╔██╗██║╚█████╗░")
    print("██║░░██╗██║░░██║██║╚████║██║░░╚██╗██╔══██╗██╔══██║░░░██║░░░██║░░░██║██║░░░░░██╔══██║░░░██║░░░██║██║░░██║██║╚████║░╚═══██╗")
    print("╚█████╔╝╚█████╔╝██║░╚███║╚██████╔╝██║░░██║██║░░██║░░░██║░░░╚██████╔╝███████╗██║░░██║░░░██║░░░██║╚█████╔╝██║░╚███║██████╔╝")
    print("░╚════╝░░╚════╝░╚═╝░░╚══╝░╚═════╝░╚═╝░░╚═╝╚═╝░░╚═╝░░░╚═╝░░░░╚═════╝░╚══════╝╚═╝░░╚═╝░░░╚═╝░░░╚═╝░╚════╝░╚═╝░░╚══╝╚═════╝░")
    time.sleep(2)
    print("Congratulations! You've won disaster dates!!")#

def game_over():
    print("Sorry unfortunately your date was unsuccessful.")
    time.sleep(1)
    print("better luck next time")
    time.sleep(2)
    print("    (;ﾟ︵ﾟ;)")
    time.sleep(1)
    Yes_or_No = input("Would you like to try again, to see if you could find your life time partner? [Y/N]?" )
    if Yes_or_No.upper() == "Y":
        print("Good luck this time round")
        disaster_dates()
    elif Yes_or_No.upper() == "N":
        time.sleep(1)
        print("░██████╗░░█████╗░███╗░░░███╗███████╗  ░█████╗░██╗░░░██╗███████╗██████╗░")
        print("██╔════╝░██╔══██╗████╗░████║██╔════╝  ██╔══██╗██║░░░██║██╔════╝██╔══██╗")
        print("██║░░██╗░███████║██╔████╔██║█████╗░░  ██║░░██║╚██╗░██╔╝█████╗░░██████╔╝")
        print("██║░░╚██╗██╔══██║██║╚██╔╝██║██╔══╝░░  ██║░░██║░╚████╔╝░██╔══╝░░██╔══██╗")
        print("╚██████╔╝██║░░██║██║░╚═╝░██║███████╗  ╚█████╔╝░░╚██╔╝░░███████╗██║░░██║")
        print("░╚═════╝░╚═╝░░╚═╝╚═╝░░░░░╚═╝╚══════╝  ░╚════╝░░░░╚═╝░░░╚══════╝╚═╝░░╚═╝")
    else:
        print("I'm sorry I didn't get that")
        game_over()

def start_game():
    print("░█████╗░░█████╗░██████╗░███████╗  ░█████╗░██████╗░░█████╗░░█████╗░██╗░░██╗███████╗██████╗░░██████╗")
    print("██╔══██╗██╔══██╗██╔══██╗██╔════╝  ██╔══██╗██╔══██╗██╔══██╗██╔══██╗██║░██╔╝██╔════╝██╔══██╗██╔════╝")
    print("██║░░╚═╝██║░░██║██║░░██║█████╗░░  ██║░░╚═╝██████╔╝███████║██║░░╚═╝█████═╝░█████╗░░██████╔╝╚█████╗░")
    print("██║░░██╗██║░░██║██║░░██║██╔══╝░░  ██║░░██╗██╔══██╗██╔══██║██║░░██╗██╔═██╗░██╔══╝░░██╔══██╗░╚═══██╗")
    print("╚█████╔╝╚█████╔╝██████╔╝███████╗  ╚█████╔╝██║░░██║██║░░██║╚█████╔╝██║░╚██╗███████╗██║░░██║██████╔╝")
    print("░╚════╝░░╚════╝░╚═════╝░╚══════╝  ░╚════╝░╚═╝░░╚═╝╚═╝░░╚═╝░╚════╝░╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝╚═════╝░")
    print()
    print("██████╗░██████╗░███████╗░██████╗███████╗███╗░░██╗████████╗░██████╗")
    print("██╔══██╗██╔══██╗██╔════╝██╔════╝██╔════╝████╗░██║╚══██╔══╝██╔════╝")
    print("██████╔╝██████╔╝█████╗░░╚█████╗░█████╗░░██╔██╗██║░░░██║░░░╚█████╗░")
    print("██╔═══╝░██╔══██╗██╔══╝░░░╚═══██╗██╔══╝░░██║╚████║░░░██║░░░░╚═══██╗")
    print("██║░░░░░██║░░██║███████╗██████╔╝███████╗██║░╚███║░░░██║░░░██████╔╝")
    print("╚═╝░░░░░╚═╝░░╚═╝╚══════╝╚═════╝░╚══════╝╚═╝░░╚══╝░░░╚═╝░░░╚═════╝░")
    time.sleep(2)
    print()
    print()
    print()
    print("██████╗░██╗░██████╗░█████╗░░██████╗████████╗███████╗██████╗░  ██████╗░░█████╗░████████╗███████╗░██████╗")
    print("██╔══██╗██║██╔════╝██╔══██╗██╔════╝╚══██╔══╝██╔════╝██╔══██╗  ██╔══██╗██╔══██╗╚══██╔══╝██╔════╝██╔════╝")
    print("██║░░██║██║╚█████╗░███████║╚█████╗░░░░██║░░░█████╗░░██████╔╝  ██║░░██║███████║░░░██║░░░█████╗░░╚█████╗░")
    print("██║░░██║██║░╚═══██╗██╔══██║░╚═══██╗░░░██║░░░██╔══╝░░██╔══██╗  ██║░░██║██╔══██║░░░██║░░░██╔══╝░░░╚═══██╗")
    print("██████╔╝██║██████╔╝██║░░██║██████╔╝░░░██║░░░███████╗██║░░██║  ██████╔╝██║░░██║░░░██║░░░███████╗██████╔╝")
    print("╚═════╝░╚═╝╚═════╝░╚═╝░░╚═╝╚═════╝░░░░╚═╝░░░╚══════╝╚═╝░░╚═╝  ╚═════╝░╚═╝░░╚═╝░░░╚═╝░░░╚══════╝╚═════╝░")
    disaster_dates()



def disaster_dates():
    print()
    print()
    print()
    print()
    print()
    print("Welcome to Disaster dating! The UK's number 1 dating game.")
    time.sleep(2)
    print("In this game you get to choose out of 4 different people you would like to take on a date.")
    time.sleep(2)
    print("The goal is to ensure you're date doesnt end in a disaster.")
    time.sleep(2)
    print()
    name = input("To start please enter your name: ")
    print()
    print("Hi {}, welcome to disaster dates".format(name))
    print()
    time.sleep(1.5)
    print("You get to choose 1 of the following 4 lovely singles. Choose carefully, some of these singles are not as good as they seem:")
    time.sleep(1.5)
    print()
    print("Single number 1")
    time.sleep(1.5)
    print("Name:        Carole Baskin")
    time.sleep(1.5)
    print("Profile:     Height 5.4', blonde hair, blue eyes.")
    time.sleep(1.5)
    print("Interests:   Cats (big cats, flower dresses, animal rights")
    time.sleep(1.5)
    print()
    print("About me:    I'm an eccentric older lady, who loves everything cat related.")
    time.sleep(1.5)
    print("             I own my own big cat rescue centre in florida. If you like feisty I'm definitely the lady for you.")
    time.sleep(1.5)
    print("             Word has it I might have killed my ex husband.")
    time.sleep(1.5)
    print()
    print("Single number 2")
    time.sleep(1.5)
    print("Name:        Prince Ali")
    time.sleep(1.5)
    print("Profile:     Height 6.5', dark hair, green eyes, own's his own accounting firm")
    time.sleep(1.5)
    print("Interests:   Loves food, nights out (party animal), self care - spa's/beauty salon, traveling and trying new things.")
    time.sleep(1.5)
    print()
    print("About me:    Prince is a young entrepreneur who loves the finer things in life.")
    time.sleep(1.5)
    print("             He has a taste for fine art and fine dinning but also loves to let his hair down and have a good time at the night club (wow let's party).")
    time.sleep(1.5)
    print("             Self care is very important to Prince and animals are a no for him.")
    time.sleep(1.5)
    print()
    print("Single number 3")
    time.sleep(1.5)
    print("Name:        Arnold Vorhese")
    time.sleep(1.5)
    print("Profile:     Height 6.5', 220lbs of pure muscle")
    time.sleep(1.5)
    print("Interests:   Pumping iron, own's the second best gym in the England.")
    time.sleep(1.5)
    print()
    print("About me:    I'm a muscular gym owner who's idol is Arnold Schwarnegger (He even kinda looks like him - but the 28 year old version!). ")
    time.sleep(1.5)
    print("             My favourite things are, working my biceps, doing pushups, and long steak dinners with protein shakes.")
    time.sleep(1.5)
    print()
    # print("Single number 4")
    # time.sleep(1.5)
    # print("Name:        Anna Jordan")
    # time.sleep(1.5)
    # print("Profile:     Height 5.6', Long brown hair, hazel eyes.")
    # time.sleep(1.5)
    # print("Interests:   Gym, Fashion, Lifestyle")
    # time.sleep(1.5)
    # print()
    # print("About me:    Anna is new to London and needs someone to show her around.")
    # time.sleep(1.5)
    # print("             Movies, friends, and beer gardens are her favourite things.")
    # time.sleep(1.5)
    # print()
    print("Now that you've been introduced to our 4 lovely single, who would you like to do on a date with?")
    date_choice = input("Please enter: 'Carole', 'Prince Ali', or 'Arnold': ")
    if date_choice.upper() == "CAROLE":
        carole_baskin()
    elif date_choice.upper() == "PRINCE ALI":
        prince_ali()
    elif date_choice.upper() == "ARNOLD":
        arnold_vorhese()
    # Arnold code
    # elif date_choice.upper == "ANNA":
    #     print("anna")
    #     # Anna code
    else:
        print("Sorry i did not recognize that. Please try again.")
        disaster_dates()

def carole_baskin():
    time.sleep(1)
    print("░█████╗░░█████╗░██████╗░░█████╗░██╗░░░░░███████╗  ██████╗░░█████╗░░██████╗██╗░░██╗██╗███╗░░██╗")
    print("██╔══██╗██╔══██╗██╔══██╗██╔══██╗██║░░░░░██╔════╝  ██╔══██╗██╔══██╗██╔════╝██║░██╔╝██║████╗░██║")
    print("██║░░╚═╝███████║██████╔╝██║░░██║██║░░░░░█████╗░░  ██████╦╝███████║╚█████╗░█████═╝░██║██╔██╗██║")
    print("██║░░██╗██╔══██║██╔══██╗██║░░██║██║░░░░░██╔══╝░░  ██╔══██╗██╔══██║░╚═══██╗██╔═██╗░██║██║╚████║")
    print("╚█████╔╝██║░░██║██║░░██║╚█████╔╝███████╗███████╗  ██████╦╝██║░░██║██████╔╝██║░╚██╗██║██║░╚███║")
    print("░╚════╝░╚═╝░░╚═╝╚═╝░░╚═╝░╚════╝░╚══════╝╚══════╝  ╚═════╝░╚═╝░░╚═╝╚═════╝░╚═╝░░╚═╝╚═╝╚═╝░░╚══╝")
    time.sleep(2)
    print("You've picked Carole, what a great choice.")
    time.sleep(2)
    print("As you read Carole is a big animal lover. We have come up with 2 different dates.")
    print()
    time.sleep(2)
    print("Date number 1 will take you and Carole on a big safari trip in Milton Keynes.")
    time.sleep(2)
    print("Date number 2 will take you and Carole on a nice Relaxing boat trip to Costa Rica.")
    time.sleep(2)
    date_carole = input("Which date will you choose? A :Date 1, or B: Date 2: ")
    if date_carole.upper() == "A":
        print("You've decided to go on date 1!")
        print()
        print()
        time.sleep(2)
        carole_baskin_date1()
    elif date_carole.upper() == "B":
        print("You've decided to go on date 2!")
        time.sleep(2)
        print("Carole seems very effacive when you mention Costa Rica. While you're waiting for her on the docks she cancels on you last minute saying she has some tiger business to take care off.")
        time.sleep(2)
        game_over()
    else:
        print("I'm sorry, I didn't recognize that. Please try again")
        time.sleep(1)
        carole_baskin()


def carole_baskin_date1():
    print("█▀▄▀█ █ █░░ ▀█▀ █▀█ █▄░█   █▄▀ █▀▀ █▄█ █▄░█ █▀▀ █▀   █▀ ▄▀█ █▀▀ ▄▀█ █▀█ █")
    print("█░▀░█ █ █▄▄ ░█░ █▄█ █░▀█   █░█ ██▄ ░█░ █░▀█ ██▄ ▄█   ▄█ █▀█ █▀░ █▀█ █▀▄ █")
    print()
    time.sleep(2)
    print("You've decided to take Carole on a day out to the safari park in Milton Keynes. Carole is super excited, and is impressed with your choice.")
    print()
    time.sleep(2)
    print("Arriving at the safari park you are greeted by the safari guide: 'Welcome to Milton Keynes Safari, my name is Dave and I'll be your guide for today.' ")
    time.sleep(1)
    print()
    print("You tell carole you think Dave looks like an egg.")
    time.sleep(2)
    print()
    time.sleep(1)
    print("She Laughs.")
    time.sleep(2)
    print()
    print("Dave explains the ins and outs of the Safari as well as the safety procedures, but you're too hypnotized by Caroles beautiful flower dress to pay attention.")
    time.sleep(1)
    print()
    print("You snap out of it and Dave asks:")
    print('"Well, which one is it? Do you want to go by Jeep or on foot?"')
    time.sleep(1)
    print()
    jeep_or_foot = input("You have the choice to make the tour by Jeep or on foot. Which one do you choose? A: Jeep, or B: Foot? ")
    if jeep_or_foot.upper() == "JEEP":
        print("                                                                              ░░░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒▓▓▓▓▓▓▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░                          ")
        print("                                                                            ▒▒▓▓▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓██▓▓▓▓▓▓▓▓▒▒██████████████████████▓▓▓▓▒▒░░                          ")
        print("                                                                          ▒▒▒▒██▒▒▒▒▒▒░░░░░░░░        ▒▒██▓▓▓▓▓▓██                ░░▓▓██  ▓▓▒▒                          ")
        print("                                                                        ░░▒▒▓▓▒▒░░                      ▓▓▓▓▓▓▒▒██                    ██▓▓▓▓▓▓░░                        ")
        print("                                                                      ░░▒▒▓▓▒▒                        ░░▓▓▓▓▓▓▓▓██                  ▒▒██████▓▓▒▒                        ")
        print("                                                                      ░░▓▓▒▒▒▒                          ▓▓▓▓▓▓▓▓██                  ▓▓████████▓▓            ▓▓          ")
        print("                                                                    ░░▒▒████  ░░                        ████▓▓▓▓██                  ░░▓▓██▓▓██▒▒          ░░▒▒▒▒▒▒▒▒░░  ")
        print("                                                                ░░▒▒▒▒████░░    ▒▒                    ░░▓▓██▓▓▓▓██                  ░░  ▓▓████▓▓▓▓        ▒▒▓▓▓▓▓▓▓▓▓▓  ")
        print("                                                            ▒▒  ▒▒▒▒██▓▓██▒▒  ░░▓▓                    ██▓▓██▓▓▓▓██                  ▒▒▓▓▓▓████▓▓██        ████▓▓▓▓████▒▒")
        print("                             ░░▒▒▒▒▒▒▒▒▒▒▒▒▓▓░░░░▒▒▒▒▓▓▒▒▓▓▒▒▒▒▓▓▓▓██▓▓▓▓▓▓██▓▓██▒▒                ▒▒▓▓▓▓██▓▓▓▓██                  ▒▒██▓▓████▓▓▓▓░░░░    ▓▓██▓▓▓▓▓▓████ ")
        print("                        ░░▒▒▒▒▒▒▓▓▓▓▒▒▒▒▒▒░░░░░░░░  ░░░░░░▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▓▓▓▓                ██▒▒▓▓██▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒▓▓▓▓▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓██")
        print("                ░░▒▒▒▒▒▒░░▒▒▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓██▓▓▓▓▒▒            ▓▓▓▓▒▒████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  ░░░░▒▒▓▓██▓▓▒▒▓▓██")
        print("                ▓▓██▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒██░░    ░░▓▓          ▒▒██▒▒▓▓████▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒▒▒▓▓██")
        print("              ▓▓██▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▓▓▓▓▓▓▓▓██░░  ░░            ░░▓▓▓▓▒▒▓▓████▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓██▓▓▓▓▓▓██")
        print("              ▒▒▓▓▓▓████████████████████▓▓▒▒▓▓▓▓▓▓██▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓████  ▓▓▓▓              ████▓▓▓▓████▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▓▓▓▓▒▒▓▓▓▓▓▓████▓▓▓▓██")
        print("            ▒▒▓▓▒▒████████████████████████▓▓▒▒▓▓▓▓▓▓██▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓██████  ▓▓▓▓▓▓▓▓▒▒░░  ▓▓░░██████████▒▒▓▓▓▓▓▓▓▓▓▓▒▒▓▓██████████████████████▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓██▓▓▓▓██")
        print("            ▓▓██████████████████████████████▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓████░░████▒▒▒▒▒▒▒▒▒▒▒▒▓▓▓▓▓▓██▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▓▓██████████████████████████▓▓▓▓▓▓▓▓▓▓▓▓████▓▓▓▓██")
        print("            ░░████████████████████████████████▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓████▓▓██▓▓▒▒▓▓▓▓▓▓▒▒▒▒▒▒▓▓▓▓▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▒▒▓▓██████████████████████████████▓▓▓▓▓▓▓▓▓▓████████▓▓")
        print("      ░░  ░░░░▓▓██████████████████████████████▓▓▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓████████▓▓▓▓▒▒▒▒▓▓▓▓▓▓▒▒▒▒▒▒▓▓██▓▓██▓▓▓▓▓▓▓▓▒▒██████████████████████████████████▓▓▓▓▓▓▓▓██████▓▓▒▒")
        print("    ░░▒▒▓▓██████████████▓▓▓▓▓▓▓▓▓▓▓▓▓▓██████████▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▓▓▓▓▓▓████████████▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓██▓▓▓▓▓▓▓▓▓▓████████████▓▓▓▓▓▓▓▓██▓▓████████████▓▓▓▓▒▒▓▓████████░░")
        print("    ▒▒▓▓▓▓████████████▓▓▓▓▓▓▒▒▓▓▒▒▒▒▓▓▓▓▓▓████████▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓████████████▓▓██████████▓▓██▓▓▓▓▓▓▓▓▓▓▓▓▓▓████████▓▓▒▒▓▓▒▒▒▒▒▒▒▒▒▒▓▓▓▓████████▓▓██▓▓▓▓▓▓▓▓▓▓▒▒  ")
        print("  ██▓▓██▓▓██████████▓▓▓▓▓▓██████████▓▓▓▓▓▓████████▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▓▓▓▓▓▓▓▓████████▓▓▓▓▒▒▓▓██████████▓▓▓▓██████████▓▓▓▓▓▓▓▓██░░    ")
        print("  ██▓▓██▓▓████████▓▓▓▓▓▓██▓▓▒▒▓▓▒▒████▓▓▓▓▓▓████████▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓████████▓▓▓▓▒▒████▒▒▓▓▒▒▒▒▓▓██▓▓▓▓▓▓██████▓▓██▓▓▓▓██░░    ")
        print("    ▓▓██████████▓▓██▓▓██▒▒░░▓▓▓▓▒▒░░▒▒██▓▓▓▓▓▓██████▓▓▓▓████▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓████████▓▓▓▓▓▓██▓▓░░▓▓▒▒▓▓▓▓░░▒▒██▓▓██████████▓▓██████      ")
        print("        ░░██████████▓▓▒▒▒▒▓▓▓▓▓▓▓▓▓▓▒▒██▓▓▓▓████████████████▓▓▓▓▓▓▓▓▓▓██▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓██████████▓▓▓▓██▒▒██▓▓▒▒▓▓████▒▒▓▓▓▓▓▓██████  ▒▒  ░░▒▒      ")
        print("          ▒▒██████▓▓▓▓▓▓▓▓▓▓██▓▓▓▓██▒▒▓▓██▓▓██████████████████████████████████████████████████████████████████████████▓▓▓▓▓▓██▓▓██▓▓▒▒▓▓▓▓██▓▓██▓▓██                    ")
        print("            ░░████▓▓▓▓▓▓██████████▓▓▓▓▒▒██▓▓██▓▓██▓▓▓▓████████▓▓████████████████████████████████████▓▓████████████████▓▓▓▓▒▒██▓▓████████▓▓██░░██▓▓██                    ")
        print("            ░░████▓▓▓▓▒▒▓▓██▓▓▓▓▓▓██▒▒▒▒██▓▓████▓▓              ▒▒░░              ░░    ░░░░░░░░░░            ░░▓▓██████▓▓▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░▓▓▓▓██                    ")
        print("              ██████▓▓░░██▓▓▓▓▓▓▓▓▓▓▓▓▒▒██▓▓████                                                                  ██████▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▓▓▓▓▒▒▓▓▓▓██                    ")
        print("              ██████▓▓▒▒▓▓██▓▓▒▒████▓▓▓▓▓▓████░░                                                                  ░░████▓▓██▒▒████▒▒██▓▓▓▓▒▒▓▓▓▓██▓▓                    ")
        print("            ░░░░██████▓▓▒▒██▒▒██▒▒▓▓▓▓██▓▓██████▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓██████▓▓██▓▓▒▒▒▒░░░░▒▒▓▓▓▓████▓▓▒▒▒▒▒▒░░░░          ")
        print("        ░░░░▒▒▒▒▒▒██████▓▓▓▓▓▓▓▓▓▓▓▓▓▓████████████████████████████████████████████████████████████████████████████████████████▓▓▓▓▓▓▓▓▓▓▓▓▓▓████▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░    ")
        print("        ░░░░░░▒▒▒▒▒▒██████▓▓▓▓██▓▓████████████████████████████████████████████████████████████████████████████████████████████████▓▓▓▓██████████▓▓▓▓▓▓▓▓▒▒▒▒▒▒░░░░      ")
        print("              ░░░░░░▒▒▓▓████████████████▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓██████████████████▓▓▓▓▓▓▒▒▒▒▒▒▒▒░░░░          ")
        carole_baskin_jeep()
    elif jeep_or_foot.upper() == "FOOT" :
        print("You've chosen to continue on foot. Carole does like a bit of a walk.")
        time.sleep(2)
        print("After walking for 10 minutes you notice you're being followed by a pack of lions")
        time.sleep(2)
        print("                                                             ░░░░    ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒░░░░░░░░▒▒░░░░")
        print("                                                     ░░░░░░▒▒▓▓▒▒▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒░░▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
        print("                                                   ░░▒▒▒▒▒▒░░▒▒▓▓▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒░░░░░░▒▒▒▒▒▒░░░░▒▒░░░░░░░░░░░░░░")
        print("                                               ░░▓▓▓▓▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░░░▒▒▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒▒▒▒▒▒▒░░░░░░░░▒▒▒▒░░░░░░")
        print("                                             ░░░░▒▒▒▒▓▓░░▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒▒▒░░░░░░░░")
        print("                                             ▒▒░░░░░░▒▒▒▒░░░░▒▒▒▒░░▒▒▒▒░░░░░░░░░░░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒░░░░░░░░░░░░░░░░")
        print("                                             ░░▒▒░░░░░░░░░░░░▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒░░░░░░░░")
        print("                                           ░░▓▓▒▒▒▒▒▒▒▒░░░░░░▒▒░░░░░░░░░░▒▒▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒▒▒▒▒")
        print("                                           ▒▒▓▓▒▒░░▒▒░░░░░░░░▒▒▒▒░░░░░░░░▒▒░░▒▒▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
        print("                                         ░░▒▒▓▓▒▒▒▒░░░░░░░░░░░░░░░░░░░░░░░░▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
        print("                                         ░░▒▒▒▒▒▒░░░░▒▒▒▒▒▒░░▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░    ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
        print("                                         ░░▒▒▒▒▒▒▒▒░░░░░░▓▓▒▒░░░░░░██▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
        print("                                         ░░▒▒▒▒▓▓▒▒▒▒░░▒▒▒▒▒▒▒▒░░▒▒▒▒░░░░░░░░▒▒▒▒░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
        print("                                         ░░▒▒▒▒▒▒▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░░░░░░░▒▒░░░░░░░░░░░░░░░░░░░░░░    ░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒░░░░")
        print("                                         ░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░░░░░▒▒▒▒▒▒░░░░░░░░▒▒░░░░░░░░░░░░░░░░░░░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
        print("                                         ░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░▒▒▒▒▒▒▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
        print("                                         ░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░▒▒▒▒▒▒▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
        print("                                           ▒▒▓▓▓▓▓▓▓▓▓▓░░▒▒▓▓▓▓▓▓▒▒░░░░░░▒▒▓▓▒▒▒▒▓▓▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
        print("                                         ░░▓▓▓▓▓▓▓▓▓▓▓▓▒▒░░░░▒▒░░░░░░░░▒▒▓▓▓▓▓▓▓▓▓▓▓▓▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒▒▒▒▒░░░░░░░░░░")
        print("                                         ░░▒▒▓▓▓▓▓▓██▓▓██████████▓▓▓▓▓▓▓▓▓▓▓▓▓▓████▓▓▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
        print("                                           ░░██▓▓▓▓██▓▓▓▓██▒▒▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓██▓▓▓▓▓▓▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
        print(" ░░░░                                      ░░▓▓████████▓▓▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓██▓▓▓▓▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
        print(" ░░░░                                        ▓▓██████████░░░░░░░░░░▓▓▒▒▓▓▓▓▓▓██▓▓▓▓▓▓▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
        print("                                             ▓▓▓▓████████▓▓▒▒▒▒▒▒▓▓▓▓▒▒▓▓▓▓▓▓▓▓▓▓██▓▓▒▒░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
        print("                                             ▓▓▓▓████████████████████████▓▓▓▓▓▓▓▓▓▓▒▒░░░░░░░░░░░░░░  ░░░░░░░░  ░░░░░░    ░░░░░░░░░░░░░░░░░░░░░░░░")
        print(" ░░                                          ▓▓▓▓██████████████████████████▓▓██████▒▒░░░░        ░░░░░░░░░░░░░░░░░░░░░░░░░░  ░░░░░░░░░░░░░░░░░░░░")
        print("     ░░                                      ▒▒▓▓▓▓▓▓██████████████████████▓▓██████▓▓░░                  ░░░░░░░░░░░░░░    ░░░░░░░░░░░░░░░░░░░░░░")
        print("     ░░░░                                    ▒▒▓▓▓▓▓▓██▓▓▓▓██████████████████████▓▓░░          ░░░░░░          ░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒░░░░░░")
        print("                                             ▒▒▓▓▒▒▒▒▒▒▓▓▓▓██████████████████████▒▒                      ░░░░░░░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
        print("                                             ░░▓▓▒▒▒▒▒▒▒▒▒▒████████████████████▓▓░░                  ░░░░░░░░░░░░░░    ░░  ░░░░    ░░░░░░░░░░░░░░")
        print("                                             ░░▓▓▒▒▒▒░░▒▒▒▒▓▓░░▒▒▓▓▒▒▒▒▒▒▓▓▓▓▓▓▒▒░░        ░░        ░░  ░░░░    ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
        print("                                             ░░▒▒▒▒▒▒░░░░░░    ▒▒▒▒▒▒▒▒▒▒▓▓▒▒░░░░░░                    ░░░░░░░░░░░░░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░")
        print("                                               ▓▓▒▒▒▒░░░░░░░░  ░░▓▓▒▒▒▒░░▒▒▒▒░░░░░░                  ░░░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
        print(" ░░░░                                          ░░▒▒▒▒▒▒░░░░░░  ░░▒▒▒▒▒▒░░▒▒░░░░░░░░        ░░          ░░░░░░░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
        print(" ░░░░░░  ░░░░░░                                ░░▓▓▒▒▒▒░░░░░░  ░░▒▒▒▒▒▒▒▒▒▒░░░░░░░░          ░░░░░░    ░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
        print(" ░░  ░░░░░░                                    ▒▒▒▒▒▒▒▒░░░░  ░░▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░░░          ░░░░            ░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒▓▓▒▒▓▓▒▒")
        print(" ░░░░░░░░                            ░░        ▒▒▒▒▒▒▒▒▒▒░░    ▒▒▒▒▒▒▒▒░░░░░░░░░░░░░░            ░░  ░░░░  ░░░░▒▒░░▒▒▒▒░░▒▒▓▓▒▒▒▒▒▒▒▒▓▓▓▓▒▒▒▒▒▒▓▓")
        print(" ░░░░  ░░      ░░                            ░░▒▒▒▒▒▒▒▒░░░░░░  ▓▓▒▒▒▒▒▒  ░░░░░░░░░░░░▒▒▒▒░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░▒▒▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓")
        print(" ░░░░░░░░  ░░░░░░                            ▒▒▒▒▒▒▒▒▒▒▒▒░░░░  ▓▓▒▒▒▒░░░░░░░░░░▒▒░░▒▒░░░░▒▒▒▒▒▒▓▓▒▒▒▒▒▒▒▒▒▒░░░░░░░░░░▒▒░░░░░░░░░░░░░░░░░░▒▒▒▒▒▒▒▒")
        print(" ░░░░        ░░  ░░  ░░  ░░▒▒  ░░░░░░  ░░░░  ▓▓▓▓▒▒▒▒░░▒▒░░▒▒░░░░▒▒░░░░▒▒░░░░░░▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒▒▒▒▒")
        print("     ░░    ░░░░░░  ░░░░    ░░  ░░░░          ▓▓▒▒▒▒▓▓  ▒▒▒▒░░░░  ░░░░░░▒▒▒▒░░░░░░    ░░░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
        print("   ░░░░░░░░  ░░░░░░░░░░░░  ░░  ░░░░░░░░        ▓▓▓▓▒▒░░░░▒▒░░░░░░▒▒░░  ▓▓▒▒▒▒▒▒▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
        print(" ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░                    ▒▒░░▒▒░░░░░░░░    ░░      ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
        print("   ░░░░░░░░░░░░░░░░░░░░  ░░░░  ░░░░    ░░            ░░  ▒▒░░░░░░░░▒▒░░░░      ░░  ░░                  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
        print(" ░░░░░░░░░░░░░░░░░░░░░░░░    ░░░░░░░░░░      ░░░░        ░░░░▒▒░░░░░░░░▒▒          ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")        
        print(" ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
        print(" ░░░░░░░░░░░░░░░░░░░░░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓▓▒▒▓▓░░▒▒▒▒▓▓░░░░░░░░░░  ░░░░  ░░░░    ░░░░  ░░    ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
        time.sleep(3)
        print("The guide tells you both not to move but its already too late.....")
        time.sleep(2)
        print("Carole not being able to contain her excitement scream of joy")
        time.sleep(1.5)
        print("Her screams set the lions into a blind rage attacking Carole.")
        print(".")
        print(".")
        print(".")
        time.sleep(1)
        print('In her last breaths she mutters "You should have chosen the Jeep, you idiot."')
        time.sleep(2)
        game_over()
    else:
        print("I'm sorry, I didn't recognize that. Please try again")
        time.sleep(1)
        carole_baskin_date1()

def carole_baskin_jeep():
    print("You've chosen Jeep as your prefered way of travel. Carole is impressed by your choice.")
    time.sleep(2)
    print("You're both enjoying the Jeep ride through the Safari Park.")
    time.sleep(2)
    print("10 minutes in a large elephant approaches the Jeep.")
    time.sleep(2)
    print("             .ed$$$$$eec.")
    print("        .e$$$$$$$$$$$$$$$$$$eeeee$$$$$c")
    print("       d$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$c")
    print("     .$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$b.")
    print("     $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ $b")
    print("    d$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$F")
    print("   .$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
    print("   $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
    print("  .$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$**$ ^$$$$")
    print("  4 $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$*      4$$F")
    print('  4  $$$$$$$$$$$$$$$$$$$$$$$$$$$"        4$$"')
    print("  4  $$$$$$$$$$$$$$$$$$$$$$$$$$$        .$$%")
    print('  d   $$$$$          $$$$$*$$$$$$c   ..e$$"')
    print('     4$$$$          ^$$$$  *$$$$$F  ^"""')
    print("      4$$$$          4$$$$ z$$$$$")
    print("      4$$$$          4$$$$ ^$$$P")
    print('      ^$$$$b          $$$$e  "f"')
    time.sleep(2)
    print("It looks hungry. Luckily you brought a snickers bar. You've got 2 choices")
    time.sleep(2)
    feed_or_not = input("Are you going to feed the snickers bar to the Elephant or keep it to yourself? A: keep, or B: feed: ")
    if feed_or_not.upper() == "B":
        time.sleep(1)
        print("You feed the elephant the snickers bar.")
        time.sleep(1)
        print(".")
        time.sleep(1)
        print(".")
        time.sleep(1)
        print(".")
        time.sleep(1)
        print("Turns out the elephant has a peanut allergy sending him straight into an anaphylactic shock. The elephant dies on the spot.")
        time.sleep(2)
        print("Carole weeps for the elephant and screams...")
        time.sleep(2)
        print("███╗░░░███╗██╗░░░██╗██████╗░██████╗░███████╗██████╗░███████╗██████╗░")
        print("████╗░████║██║░░░██║██╔══██╗██╔══██╗██╔════╝██╔══██╗██╔════╝██╔══██╗")
        print("██╔████╔██║██║░░░██║██████╔╝██║░░██║█████╗░░██████╔╝█████╗░░██████╔╝")
        print("██║╚██╔╝██║██║░░░██║██╔══██╗██║░░██║██╔══╝░░██╔══██╗██╔══╝░░██╔══██╗")
        print("██║░╚═╝░██║╚██████╔╝██║░░██║██████╔╝███████╗██║░░██║███████╗██║░░██║")
        print("╚═╝░░░░░╚═╝░╚═════╝░╚═╝░░╚═╝╚═════╝░╚══════╝╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝")
        time.sleep(2)
        print("It is safe to say this date is over and you return to the entrance where Carole says she never wants to see you again.")
        game_over()
    elif feed_or_not.upper() == "A":
        print("Keep your Snickers to yourself.")
        time.sleep(2)
        carole_baskin_keep()
    else:
        print("I'm sorry, I didn't recognize that. Please try again.")
        time.sleep(1)
        carole_baskin_jeep

def carole_baskin_keep():
    print("You decided to not feed the animal junkfood. The elephant leaves the 2 of you alone and goes looking for food somewhere else. Nobody was harmed and the ride continues.")
    time.sleep(2)
    print("You are both really enjoying the safari ride. Everything seems to be going well.")
    print(".")
    time.sleep(2)
    print(".")
    time.sleep(2)
    print(".")
    time.sleep(2)
    print("Almost too well...")
    time.sleep(2)
    print("░██╗░░░░░░░██╗██╗░░██╗██████╗░")
    print("░██║░░██╗░░██║██║░██╔╝██╔══██╗")
    print("░╚██╗████╗██╔╝█████═╝░██║░░██║")
    print("░░████╔═████║░██╔═██╗░██║░░██║")
    print("░░╚██╔╝░╚██╔╝░██║░╚██╗██████╔╝")
    print("░░░╚═╝░░░╚═╝░░╚═╝░░╚═╝╚═════╝░")
    print("So you decide to pull out a litre bottle of WKD blue and ask Carole if she wants a sip. Carole seems a bit hesitant since drinking is not allowed on the safari trip.")
    time.sleep(2)
    drink_choice = input("You're left with 2 choices either offer Carole a sip anyway, or put the bottle away. A: Offer, or B: leave: ")
    if drink_choice.upper() == "A":
        print("You tell Carole its alright and pressure her into taking a sip of WKD blue.")
        time.sleep(2)
        print("Carole takes a sip,")
        time.sleep(2)
        print("and another sip")
        time.sleep(2)
        print("and another sip")
        time.sleep(2)
        print("AND ANOTHER...")
        time.sleep(2)
        print("Carole manages to chuck the entire bottle of WKD in less than 10 seconds. Turns out Carole is a raging alcoholic.")
        time.sleep(2)
        print("Now intoxicated Carole spots a couple of lions and decides now is a good time to jump out of the Jeep and approach the pack. ")
        time.sleep(2)
        print("The lions feel comforted by Caroles presence treating her as one of their own.")
        time.sleep(2)
        print("Carole decides to stay with the lions and tells you to leave.")
        time.sleep(2)
        print("Your date ends.")
        time.sleep(2)
        print("That'll teach you not to pressure someone into dangerous alcohol consumption.")
        game_over()
    elif drink_choice.upper() == "B":
        print("You put the bottle away and agree this is not the appropriate time to drink. ")
        time.sleep(2)
        carole_baskin_not_offer()
    else:
        print("I'm sorry, I didn't recognize that. Please try again")
        time.sleep(1)
        carole_baskin_keep()

def carole_baskin_not_offer():
    print("Carole thanks you for your understanding. The date continues. ")
    time.sleep(2)
    print()
    print("While driving though the park Carole spots a pack of lions. She ask the tour guide to pull in closer.")
    time.sleep(2)
    print()
    print("The lions are intrigued by your presence. One of them comes up to the car.")
    time.sleep(2)
    print("                                                             ░░░░    ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒░░░░░░░░▒▒░░░░")
    print("                                                     ░░░░░░▒▒▓▓▒▒▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒░░▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
    print("                                                   ░░▒▒▒▒▒▒░░▒▒▓▓▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒░░░░░░▒▒▒▒▒▒░░░░▒▒░░░░░░░░░░░░░░")
    print("                                               ░░▓▓▓▓▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░░░▒▒▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒▒▒▒▒▒▒░░░░░░░░▒▒▒▒░░░░░░")
    print("                                             ░░░░▒▒▒▒▓▓░░▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒▒▒░░░░░░░░")
    print("                                             ▒▒░░░░░░▒▒▒▒░░░░▒▒▒▒░░▒▒▒▒░░░░░░░░░░░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒░░░░░░░░░░░░░░░░")
    print("                                             ░░▒▒░░░░░░░░░░░░▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒░░░░░░░░")
    print("                                           ░░▓▓▒▒▒▒▒▒▒▒░░░░░░▒▒░░░░░░░░░░▒▒▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒▒▒▒▒")
    print("                                           ▒▒▓▓▒▒░░▒▒░░░░░░░░▒▒▒▒░░░░░░░░▒▒░░▒▒▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
    print("                                         ░░▒▒▓▓▒▒▒▒░░░░░░░░░░░░░░░░░░░░░░░░▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
    print("                                         ░░▒▒▒▒▒▒░░░░▒▒▒▒▒▒░░▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░    ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
    print("                                         ░░▒▒▒▒▒▒▒▒░░░░░░▓▓▒▒░░░░░░██▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
    print("                                         ░░▒▒▒▒▓▓▒▒▒▒░░▒▒▒▒▒▒▒▒░░▒▒▒▒░░░░░░░░▒▒▒▒░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
    print("                                         ░░▒▒▒▒▒▒▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░░░░░░░▒▒░░░░░░░░░░░░░░░░░░░░░░    ░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒░░░░")
    print("                                         ░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░░░░░▒▒▒▒▒▒░░░░░░░░▒▒░░░░░░░░░░░░░░░░░░░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
    print("                                         ░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░▒▒▒▒▒▒▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
    print("                                         ░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░▒▒▒▒▒▒▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
    print("                                           ▒▒▓▓▓▓▓▓▓▓▓▓░░▒▒▓▓▓▓▓▓▒▒░░░░░░▒▒▓▓▒▒▒▒▓▓▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
    print("                                         ░░▓▓▓▓▓▓▓▓▓▓▓▓▒▒░░░░▒▒░░░░░░░░▒▒▓▓▓▓▓▓▓▓▓▓▓▓▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒▒▒▒▒░░░░░░░░░░")
    print("                                         ░░▒▒▓▓▓▓▓▓██▓▓██████████▓▓▓▓▓▓▓▓▓▓▓▓▓▓████▓▓▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
    print("                                           ░░██▓▓▓▓██▓▓▓▓██▒▒▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓██▓▓▓▓▓▓▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
    print(" ░░░░                                      ░░▓▓████████▓▓▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓██▓▓▓▓▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
    print(" ░░░░                                        ▓▓██████████░░░░░░░░░░▓▓▒▒▓▓▓▓▓▓██▓▓▓▓▓▓▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
    print("                                             ▓▓▓▓████████▓▓▒▒▒▒▒▒▓▓▓▓▒▒▓▓▓▓▓▓▓▓▓▓██▓▓▒▒░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
    print("                                             ▓▓▓▓████████████████████████▓▓▓▓▓▓▓▓▓▓▒▒░░░░░░░░░░░░░░  ░░░░░░░░  ░░░░░░    ░░░░░░░░░░░░░░░░░░░░░░░░")
    print(" ░░                                          ▓▓▓▓██████████████████████████▓▓██████▒▒░░░░        ░░░░░░░░░░░░░░░░░░░░░░░░░░  ░░░░░░░░░░░░░░░░░░░░")
    print("     ░░                                      ▒▒▓▓▓▓▓▓██████████████████████▓▓██████▓▓░░                  ░░░░░░░░░░░░░░    ░░░░░░░░░░░░░░░░░░░░░░")
    print("     ░░░░                                    ▒▒▓▓▓▓▓▓██▓▓▓▓██████████████████████▓▓░░          ░░░░░░          ░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒░░░░░░")
    print("                                             ▒▒▓▓▒▒▒▒▒▒▓▓▓▓██████████████████████▒▒                      ░░░░░░░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
    print("                                             ░░▓▓▒▒▒▒▒▒▒▒▒▒████████████████████▓▓░░                  ░░░░░░░░░░░░░░    ░░  ░░░░    ░░░░░░░░░░░░░░")
    print("                                             ░░▓▓▒▒▒▒░░▒▒▒▒▓▓░░▒▒▓▓▒▒▒▒▒▒▓▓▓▓▓▓▒▒░░        ░░        ░░  ░░░░    ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
    print("                                             ░░▒▒▒▒▒▒░░░░░░    ▒▒▒▒▒▒▒▒▒▒▓▓▒▒░░░░░░                    ░░░░░░░░░░░░░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░")
    print("                                               ▓▓▒▒▒▒░░░░░░░░  ░░▓▓▒▒▒▒░░▒▒▒▒░░░░░░                  ░░░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
    print(" ░░░░                                          ░░▒▒▒▒▒▒░░░░░░  ░░▒▒▒▒▒▒░░▒▒░░░░░░░░        ░░          ░░░░░░░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
    print(" ░░░░░░  ░░░░░░                                ░░▓▓▒▒▒▒░░░░░░  ░░▒▒▒▒▒▒▒▒▒▒░░░░░░░░          ░░░░░░    ░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
    print(" ░░  ░░░░░░                                    ▒▒▒▒▒▒▒▒░░░░  ░░▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░░░          ░░░░            ░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒▓▓▒▒▓▓▒▒")
    print(" ░░░░░░░░                            ░░        ▒▒▒▒▒▒▒▒▒▒░░    ▒▒▒▒▒▒▒▒░░░░░░░░░░░░░░            ░░  ░░░░  ░░░░▒▒░░▒▒▒▒░░▒▒▓▓▒▒▒▒▒▒▒▒▓▓▓▓▒▒▒▒▒▒▓▓")
    print(" ░░░░  ░░      ░░                            ░░▒▒▒▒▒▒▒▒░░░░░░  ▓▓▒▒▒▒▒▒  ░░░░░░░░░░░░▒▒▒▒░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░▒▒▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓")
    print(" ░░░░░░░░  ░░░░░░                            ▒▒▒▒▒▒▒▒▒▒▒▒░░░░  ▓▓▒▒▒▒░░░░░░░░░░▒▒░░▒▒░░░░▒▒▒▒▒▒▓▓▒▒▒▒▒▒▒▒▒▒░░░░░░░░░░▒▒░░░░░░░░░░░░░░░░░░▒▒▒▒▒▒▒▒")
    print(" ░░░░        ░░  ░░  ░░  ░░▒▒  ░░░░░░  ░░░░  ▓▓▓▓▒▒▒▒░░▒▒░░▒▒░░░░▒▒░░░░▒▒░░░░░░▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒▒▒▒▒")
    print("     ░░    ░░░░░░  ░░░░    ░░  ░░░░          ▓▓▒▒▒▒▓▓  ▒▒▒▒░░░░  ░░░░░░▒▒▒▒░░░░░░    ░░░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
    print("   ░░░░░░░░  ░░░░░░░░░░░░  ░░  ░░░░░░░░        ▓▓▓▓▒▒░░░░▒▒░░░░░░▒▒░░  ▓▓▒▒▒▒▒▒▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
    print(" ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░                    ▒▒░░▒▒░░░░░░░░    ░░      ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
    print("   ░░░░░░░░░░░░░░░░░░░░  ░░░░  ░░░░    ░░            ░░  ▒▒░░░░░░░░▒▒░░░░      ░░  ░░                  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
    print(" ░░░░░░░░░░░░░░░░░░░░░░░░    ░░░░░░░░░░      ░░░░        ░░░░▒▒░░░░░░░░▒▒          ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")        
    print(" ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
    print(" ░░░░░░░░░░░░░░░░░░░░░░░░  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓▓▒▒▓▓░░▒▒▒▒▓▓░░░░░░░░░░  ░░░░  ░░░░    ░░░░  ░░    ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░")
    time.sleep(2)
    print("It looks like it wants to be stroked.")
    time.sleep(2)
    stroke_or_not = input("You're left with 2 choices: Roll the window down and stroke the tiger or leave the window closed. A: Stroke, or B: Leave: ")
    if stroke_or_not.upper() == "A":
        print("You roll down your window and stroke the lion.")
        time.sleep(2)
        winner_chicken()
    elif stroke_or_not.upper() == "B":
        print("You decided to be smart and leave the window closed. ")
        time.sleep(2)
        print("The lion looks almost offended and leaves the car alone. ")
        time.sleep(2)
        print("The date end. Carole says she's had a nice time but doesn't really see this going anywhere.")
        time.sleep(2)
        print("She says: 'I just don't feel you share the same love for animals as I do.")
        time.sleep(2)
        print("While she walks away, you think to yourself.")
        time.sleep(2)
        print(".")
        time.sleep(1)
        print(".")
        time.sleep(1)
        print(".")
        time.sleep(1)
        print("Should I have stroked that lion?")
        time.sleep(2)
        game_over()

def winner_chicken():
    print("The lion seems very please with your stroke at first, that is until you accidentally touch his ear. ")
    time.sleep(2)
    print("The lion hates people touching his ears and.")
    time.sleep(1)
    print(".")
    time.sleep(1)
    print(".")
    time.sleep(1)
    print(".")
    time.sleep(2)
    print("He rips your arm clean off! ")
    time.sleep(2)
    print("Carole jumps out of the car and scares away the tiger.")
    time.sleep(2)
    print("Even thou you lost an arm, Carole still admires your bravery for stroking the animal.")
    time.sleep(2)
    print("It is there she falls in love with you.")
    time.sleep(2)
    print("░░▄███▄███▄")
    print("░░█████████")
    print("░░▒▀█████▀░")
    print("░░▒░░▀█▀")
    print("░░▒░░█░")
    print("░░▒░█")
    print("░░░█")
    print("░░█░░░░███████")
    print("░██░░░██▓▓███▓██▒")
    print("██░░░█▓▓▓▓▓▓▓█▓████")
    print("██░░██▓▓▓(◐)▓█▓█▓█")
    print("███▓▓▓█▓▓▓▓▓█▓█▓▓▓▓█")
    print("▀██▓▓█░██▓▓▓▓██▓▓▓▓▓█")
    print("░▀██▀░░█▓▓▓▓▓▓▓▓▓▓▓▓▓█")
    print("░░░░▒░░░█▓▓▓▓▓█▓▓▓▓▓▓█")
    print("░░░░▒░░░█▓▓▓▓█▓█▓▓▓▓▓█")
    print("░░░░▒░░░█▓▓▓▓█▓█▓▓▓▓▓█")
    print("░▒░░▒░░░█▓▓▓█▓▓▓█▓▓▓▓█")
    print("░▒░░▒░░░█▓▓▓█░░░█▓▓▓█")
    print("░▒░░▒░░██▓██░░░██▓▓██")
    print("████████████████████████")
    print("█▄─▄███─▄▄─█▄─█─▄█▄─▄▄─█")
    print("██─██▀█─██─██─█─███─▄█▀█")
    print("▀▄▄▄▄▄▀▄▄▄▄▀▀▄▄▄▀▀▄▄▄▄▄▀")
    time.sleep(2)
    print("She kisses you and asks you out on a second date!")
    congratulations()

def prince_ali():
    print()
    print("You've picked Prince, what a great choice.")
    time.sleep(1)
    print("As you read Prince likes to take care of his personal apperance and loves the finer things in life. We have come up with 2 different dates")
    time.sleep(1)
    print()
    print("Date number 1 will take you and Prince on a romantic hot air balloon ride.")
    time.sleep(1)
    print("Date number 2 will take you on a nice romantic dinner at a Michelin star restaurant")
    time.sleep(1)
    print()
    date_Prince = input("Which date will you choose? A :Date 1, or B: Date 2: ")
    if date_Prince.upper() == "A":
        print("You've decided to go on date 1!")
        time.sleep(2)
        prince_ali_date1()
    elif date_Prince.upper() == "B":
        print("You've decided to go on date 2!")
        time.sleep(2)
        prince_ali_date2()
    else:
        print("I'm sorry I don't reconize that. Please try again")
        time.sleep(1)

    
def prince_ali_date1():
    print("                                 _ .--.")
    print("                                ( `    )")
    print("                             .-'      `--,")
    print("                  _..----.. (             )`-.")
    print("                .'_|` _|` _|(  .__,           )")
    print("               /_|  _|  _|  _(        (_,  .-'")
    print("              ;|  _|  _|  _|  '-'__,--'`--'")
    print("              | _|  _|  _|  _| |")
    print("          _   ||  _|  _|  _|  _|")
    print("        _( `--.\_|  _|  _|  _|/")
    print("     .-'       )--,|  _|  _|.`")
    print("    (__, (_      ) )_|  _| /")
    print("   jgs`-.__.\ _,--'\|__|__/")
    print("                    ;____;")
    print("                     \YT/")
    print("                      ||")
    print("                     |""|")
    print("                     '=='")
    time.sleep(2)
    print("Great choice of date, what could be better than the cool country air in your hair with a handsome man. Grab your goggles cause you're in for a memorable experience.")
    time.sleep(2)
    print("As you both approach the hot air balloon Prince assists you climb into the basket. You think to yourself what a perfect gentleman.")
    time.sleep(2)
    print("As soon as you both think the date is going well, you notice a herd of vultures starting to surround the hot air balloon ready to attack. What do you do? ")
    time.sleep(1)
    print()
    print("OPTION A: Throw down the escape ladder that's in the basket of the hot air balloon and attempt to go down it? ")
    time.sleep(1)
    print("OPTION B: Hold on tight to your date in hopes that he will protect you and the vultures will eventually go away? ")
    print()
    OPTION_A_or_OPTION_B = input("What will it be OPTION A OR B? ")
    if OPTION_A_or_OPTION_B.upper() == "A":
        print("You've chosen option A, to climb down the ladder")
        time.sleep(2)
        print("Was that the right choice?. Let's see?")
        time.sleep(2)
        prince_ladder()
    elif OPTION_A_or_OPTION_B.upper() == "B":
        print("You've chosen option B, to hold on tight to your Prince charming")
        time.sleep(2)
        print("Is he the Prince charming that you thought he will be?. Let's see")
        time.sleep(1)
        prince_hold_on_tight()
    else:
        print("I'm sorry I don't reconize that. Please try again")
        time.sleep(1)
        prince_ali_date1()

def prince_ladder():
    print()
    print("As you begin to climb down the rope ladder a huge gust of wind blows by and begins the shake the ladder.")
    time.sleep(2)
    print("In this case what do you do? ")
    time.sleep(1)
    print()
    print("OPTION A: Attempt to climb back up the ladder?")
    time.sleep(1)
    print("OPTION B: Hold on tight until the wind passes by?")
    time.sleep(1)
    print()
    OPTION_A_or_OPTION_B = input("What will be your decision for survival? ")
    if OPTION_A_or_OPTION_B.upper() == "A":
        print("As you begin to climb up the ladder and you get half way up, your foot slips and you plummet to your demise.")
        time.sleep(1)
        game_over()
    elif OPTION_A_or_OPTION_B.upper() == "B":
        print("As you decide to hold on tight a vulture comes and pecks your eye, you raise one hand to shield yourself and all of sudden in attempt to scare of the vulture you lose your grip and plummet to the ground.")
        time.sleep(1)
        game_over()
    else:
        print("I'm sorry I don't reconize that. Please try again")
        time.sleep(1)
        prince_ladder()

def prince_hold_on_tight():
    print()
    print("         ........  /   |_ ........")
    print("      .........../     /............")
    print("    ............/      >..............")
    print("  .............(      >................")
    print(" ............./      /..................")
    print("............./     /.....................")
    print("............/      /.....................")
    print(".........__/      \_____.................")
    print(" ......./'             |................")
    print("  ......./     /-\     /...............")
    print("   ...../      /  \--/................")
    print("    .../     /.......................")
    print("      /      /.....................")
    print("     (      >....................")
    print("    /      >...................")
    print("   /     _| .................")
    print("  /  __/      .............")
    print(" /_/            .........")
    print("                  .....")
    print("                   ...")
    print("As soon as you try to hold on tight to Prince he immediately pushes you off him in fear that his perfect hair and stunning face will be ruined and takes cover underneath a throw he finds in the hot air balloon basket.")
    time.sleep(2)
    print("You now have 2 choices for survival at this stage:")
    time.sleep(2)
    print()
    print("OPTION A: Attempt to take down the hot air balloon yourself for a safe landing")
    time.sleep(1)
    print("OPTION B: Hold on tight hoping and praying the vultures will eventually get bored and tired and go away")
    print()
    OPTION_A_or_OPTION_B = input("What will be your decision for survival? ")
    if OPTION_A_or_OPTION_B.upper() == "B" or OPTION_A_or_OPTION_B.upper() == "OPTION B":
        print("Wrong choice hungry vultures never get tired.")
        time.sleep(2)
        print("You and Prince face a gruesome attack from the hungry vultures.")
        time.sleep(2)
        print("Guess you wont be seeing each other again")
        game_over()
    elif OPTION_A_or_OPTION_B.upper() == "A" or OPTION_A_or_OPTION_B.upper() == "OPTION A":
        print("Great job! You did well, who taught you how to land a hot a balloon like that.")
        time.sleep(1)
        prince_second_date()
    else:
        print("I'm sorry I don't reconize that. Please try again")
        time.sleep(1)
        prince_hold_on_tight()

def prince_ali_date2():
    print()
    print(" {-}")
    print(" |(|")
    print(" |=|")
    print("/   |")
    print("|.--|")
    print("||  |")
    print("||  |    .    ' .")
    print("|'--|  '     \~~~/")
    print("'-=-' \~~~/   \_/")
    print("       \_/     Y")
    print("        Y     _|_")
    print("jgs    _|_")
    time.sleep(2)
    print("Make room for some delicious food, cause you'll be eating well tonight with Prince charming")
    time.sleep(2)
    print("As you approch the restaurant you are nervous yet excited. You have been waiting for Mr Perfect to sweep you off your feet for a very long time")
    time.sleep(2)
    print("Prince see's you walk into the restaurant and realises you had dated his friend and slip's out the back door of the restaurant. Sorry look's like you've been stood up.")
    game_over()

def prince_second_date():
    print()
    print("What an adventure for a first blind date?" )
    time.sleep(1)
    print()
    Yes_or_No = input("Would you like to see Prince Ali again [Y/N]?" )
    if Yes_or_No.upper() == "Y":
        print("Maybe something indoors will be safer this time")
        congratulations()
    elif Yes_or_No.upper() == "N":
        print("Better luck next time")
        time.sleep(1)
        game_over()
    else:
        print("I'm sorry I don't reconize that. Please try again")
        time.sleep(1)
        prince_second_date()
        
def arnold_vorhese():
    print("Nice one! You will be going on a date with Arnold Vorhese:)")    
    print()
    print()                                                                                                             
    time.sleep(1.5)
    print("  /$$$$$$                            /$$      /$$       /$$    /$$                 /$$                                   ")              
    print(" /$$__  $$                          | $$     | $$      | $$   | $$                | $$                                   ")         
    print("| $$  \ $$ /$$$$$$ /$$$$$$$  /$$$$$$| $$ /$$$$$$$      | $$   | $$/$$$$$$  /$$$$$$| $$$$$$$  /$$$$$$  /$$$$$$$ /$$$$$$    ")
    print("| $$$$$$$$/$$__  $| $$__  $$/$$__  $| $$/$$__  $$      |  $$ / $$/$$__  $$/$$__  $| $$__  $$/$$__  $$/$$_____//$$__  $$   ")
    print("| $$__  $| $$  \__| $$  \ $| $$  \ $| $| $$  | $$       \  $$ $$| $$  \ $| $$  \__| $$  \ $| $$$$$$$|  $$$$$$| $$$$$$$$   ")
    print("| $$  | $| $$     | $$  | $| $$  | $| $| $$  | $$        \  $$$/| $$  | $| $$     | $$  | $| $$_____/\____  $| $$_____/   ")
    print("| $$  | $| $$     | $$  | $|  $$$$$$| $|  $$$$$$$         \  $/ |  $$$$$$| $$     | $$  | $|  $$$$$$$/$$$$$$$|  $$$$$$$   ")
    print("|__/  |__|__/     |__/  |__/\______/|__/\_______/          \_/   \______/|__/     |__/  |__/\_______|_______/ \_______/   ")
    print()
    print("Arnold loves the gym!")
    time.sleep(1)
    print("Same may call him a gym rat. He is also a big Arnold Schwarenegger fan.")
    time.sleep(1)
    print()
    print("You now have a choice of two dates:")
    time.sleep(2)
    print("Date number 1 is going to the cinema to watch a classic Arnold Schwarzenegger movie: The Terminator!")
    time.sleep(1)
    print("Date number 2 is an exciting outdoor bootcamp on a lovely sunny day in the park.")
    time.sleep(1)
    date_arnold_vorhese = input("So, which date takes your fancy? 'Date 1' or 'Date 2':")
    if date_arnold_vorhese.upper()=="DATE 1":
        print("Date 1 it is! You will be watching THE TERMINATOR with Arnold Vorhese :)")
        time.sleep(1.5)
        print()
        print("You arrive at the cinema on time....But Arnold is nowhere to be found.")
        print()
        print()
        time.sleep(1.5)
        print("Arnold later sends a text saying 'Im sorry! I haven't finished my workout. I think i will give this date a skip!")
        print()
        game_over()
    elif date_arnold_vorhese.upper()=="DATE 2":
        print("Great stuff! You chose to go on the outdoor bootcamp. Get your sports shoes ready: )")
        arnold_date1()
    else:
        print("I'm sorry, I didnt recognise that.Please try again")
        time.sleep(1)
        arnold_vorhese()
        
def arnold_date1():
    print("Arnold is excited to show you his training skills and have you meet some of his gym friends.")
    time.sleep(1.5)
    print()
    print()
    print("  ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶ ")
    print("  ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶11_____1¶¶¶¶¶¶¶ ")
    print("  ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶1__________1¶¶¶¶¶ ")
    print("  ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶1_____________¶¶¶¶ ")
    print("  ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶_______________¶11 ")
    print("  ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶1__________________ ")
    print("  ¶¶¶¶¶¶¶1____1¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶1________________¶¶ ")
    print("  ¶¶¶¶¶__________¶¶¶¶¶¶¶¶¶¶¶11____________________¶¶ ")
    print("  ¶¶¶¶____________¶¶¶¶11_____11___1______________1¶¶ ")
    print("  ¶¶¶1__________________11¶¶¶¶¶__1¶1_____________¶¶¶ ")
    print("  ¶¶¶1_______________¶¶¶¶¶¶¶¶¶¶__1¶¶¶__________1¶¶¶¶ ")
    print("  ¶¶¶______________1¶¶¶¶¶¶¶¶¶¶____¶¶¶¶¶11__111¶¶¶¶¶¶ ")
    print("  ¶¶¶1_____________¶¶¶¶¶¶¶¶¶¶¶____¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶ ")
    print("  ¶¶¶¶¶____________¶¶____1¶¶¶¶____¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶ ")
    print("  ¶¶¶¶¶¶___________________¶¶1___1¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶ ")
    print("  ¶¶¶¶¶¶¶¶11111¶1__________¶1____¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶ ")
    print("  ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶_________1¶_____¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶ ")
    print("  ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶_______________1¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶ ")
    print("  ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶_______________¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶ ")
    print("  ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶_____________1¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶ ")
    print("  ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶1_____________¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶ ")
    print("  ¶¶¶¶¶¶¶¶¶¶¶¶¶¶1____________1¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶ ")
    print("  ¶¶¶¶¶¶¶¶¶¶¶¶¶¶1____________¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶ ")
    print("  ¶¶¶¶¶¶¶¶¶¶¶¶¶¶1___________1¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶ ")
    print("  ¶¶¶¶¶¶¶¶¶¶¶¶¶¶____________¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶ ")
    print("  ¶¶¶¶¶¶¶¶¶¶¶¶¶¶1___________1¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶ ")
    print("  ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶1___________1¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶ ")
    print()
    print()
    time.sleep(1.5)
    print("You meet Arnold in Greenwich Park. There are a bunch of sporty friends of his all raring to go and work out. You feel ready to give your best!")
    time.sleep(2)
    print()
    print("You start and the workout is going well! The sun is high and you start to sweat. Arnold is impressed and compliments your form;)")
    print("                       |                            ")
    print("                  .    |                            ")
    print("                       |                            ")
    print("       \    *          |     *  .  /                  ")
    print("         \          *  |  .      /                    ")
    print("       .    \      ___---___     /    .               ")
    print("              \.--          --./                     ")
    print("   ~-_    *  ./                \.   *   _-~           ")
    print("       ~-_   /                   \   _-~     *       ")
    print("  *      ~-/                       \-~                ")
    print("    .     |                         |      .          ")
    print("        *|                           | *              ")
    print("--------|                             |-----------    ")
    print("  .      |                           |        .      ")
    print("        * |                         | *              ")
    print("          _-\                     /-_    *           ")
    print("    .  _-~ . \                   /   ~-_             ")
    print("    _-~       `\               /'*      ~-_          ")
    print("   ~           /`--___   ___--'\           ~         ")
    print("          *  /        ---     .  \                   ")
    print("           /     *     |           \                 ")
    print("         /             |   *         \               ")
    print("                    .  |        .                    ")
    print("                       |                             ")
    print("                       |                             ")
    print()
    time.sleep(1.5)
    print()
    print("All of a sudden you feel lightheaded. You think 'Oh dear, I am getting heat stroke!'")
    time.sleep(1.5)
    print()
    stop_or_continue = input("You realise you only have two choices: 1. You could STOP and grab a drink or 2. CONTINUE and exercise less:")
    if stop_or_continue.upper() == "STOP":
        arnold_stop()
    elif stop_or_continue.upper() == "CONTINUE":
        print()
        print("You decide to continue and the exercise keeps getting harder.")
        time.sleep(1.5)
        print("After some time you begin to loose sensation in your legs.")
        time.sleep(1.5)
        print("Suddenly you fall and pass out!")
        time.sleep(1.5)
        print()
        print("When you get up you find everyone has left you and gone to the pub...the date is all over...")
        game_over()
    else:
        print("I'm sorry, I didn't recognize that. Please try again")
        time.sleep(1.5)
        arnold_date1()
def arnold_stop():
    print()
    print("You thought it best to stop and have a breather whilst getting some water.")
    time.sleep(1.5)
    print("Arnold asks one of his mates to take over and comes to your side.")
    print()
    time.sleep(1.5)
    print("'Are you ok?' he asks. 'Sure, just a bit breathless' you say. Arnold then suggests you take a WALK with him if you like or you could WAIT until the session ends...")
    print()
    print()
    walk_or_wait = input("You can now choose to either WALK with him or WAIT for the session to end:")
    if walk_or_wait.upper() == "WALK":
        time.sleep(1.5)
        print()
        print()
        print("you go for a walk with Arnold...")
        print()
        time.sleep(1.5)
        print("he seems really sweet and holds you hand:)")
        time.sleep(1.5)
        print()
        print("but while he walks all he can do is talk about his biceps and the gym!")
        print()
        time.sleep(1.5)
        print("you grow tired of his talking and want to change subject...")
        print()
        time.sleep(1.5)
        print("As soon as you change the subject Arnold starts crying uncontrollably.")
        print()
        time.sleep(1.5)
        print("He says 'You dont care about me or anything that I do! You dont love me at all!")
        print()
        time.sleep(1.5)
        print("You decide to leave the scene as quickly as possible and to not speak to him again...")
        game_over()
    elif walk_or_wait.upper()=="WAIT":
        print("You think it is better to wait and relax for a bit until the session ends")
        time.sleep(1.5)
        arnold_wait()
    else:
        print("I'm sorry, I didn't recognize that. Please try again")
        time.sleep(1.5)
        arnold_stop()
def arnold_wait():
    print()
    print("Arnold admires your effort and your ability to know your limits. He wants to continue the date after the training")
    time.sleep(1.5)
    print()
    print("Once the training is done, Arnold asks if you would like to get a coffee at the cafe in his gym?")
    time.sleep(1.5)
    print()
    print("You decide to go... When you arrive there are so many people packed inside the gym.")
    time.sleep(1.5)
    print()
    print("Everyone is screaming and shouting whilst working out. In the corner, a guy just had a large weight fall on his head! You ask Arnold if you should help him?")
    time.sleep(1.5)
    print()
    print("Arnold says 'Oh, that happens all the time. He probably has brain damage now. Pay it no mind")
    time.sleep(1.5)
    print()
    help_or_coffee = input("You dont know what to do now...should you 1. Go and HELP the guy or 2. Walk away and get your COFFEE with Arnold?:")
    if help_or_coffee.upper() =="HELP":
        print()
        print("You decide to go and help the man out.")
        print()
        time.sleep(1.5)
        print("The man is out cold. You feel his pulse and it seems he is...dead.")
        print()
        time.sleep(1.5)
        print("But, all of a sudden, he jumps up and starts walking...he has become a zombie!")
        time.sleep(1.5)
        print()
        print("Arnold screams'You shouldn't have touched his pulse! He has become a zombie now! We are done now!")
        print()
        print("                      .....                 ")
        print("                      C C  /                ") 
        print("                     /<   /             ")
        print("           ___ __________/_#__=o       ")      
        print("     /(- /(\_\________   \              ")  
        print("     \ ) \ )_      \o     \             ")
        print("     /|\ /|\       |'     |             ")
        print("                   |     _|             ")
        print("                   /o   __\             ")
        print("                  / '     |             ")
        print("                 / /      |             ")
        print("                /_/\______|             ")
        print("               (   _(    <              ")
        print("                \    \    \             ")
        print("                 \    \    |            ")
        print("                  \____\____\          ")
        print("                  ____\_\__\_\          ")
        print("                 /`   /`     o\         ")
        print("                 |___ |_______|..       ")

        time.sleep(1)
        print("Everyone runs out of the gym in panic. You start to run with them. You trip...you fall...you are eaten up by the zombie!!!")
        game_over()
    elif help_or_coffee.upper() == "COFFEE":
        time.sleep(1)
        print("you decide to get the coffee and leave the man alone. 'Arnold knows his gym and the people in it' you say to yourself")
        arnold_coffee()
    else:
        print("I'm sorry, I didn't recognize that. Please try again")
        time.sleep(1)
        arnold_wait()
def arnold_coffee():
    print ("you go for a coffee with Arnold and he is super charming and funny!")
    print()
    time.sleep(1.5)
    print ("he compliments your looks and starts moving closer to you")
    print()
    time.sleep(1.5)
    print("you can sense that he wants to kiss you")
    print()
    time.sleep(1.5)
    print()
    kiss_or_not = input("You now need to decide. Will you take it to the next level and KISS Arnold, or do you WAIT for a better time?")
    if kiss_or_not.upper() == "KISS":
        print("You reach in for a kiss and Arnold smiles and comes closer...")
        print()
        time.sleep(1.5)
        print("...but all of a sudden, he goes for your neck")
        print()
        time.sleep(1.5)
        print("before you have time to think, fangs grow from his teeth and he bites your neck")
        print()
        time.sleep(1.5)
        print("turns out Arnold was a bodybuilding Vampire who has lived in London for 200 years!")
        print()
        game_over()
    elif kiss_or_not.upper() == "WAIT":
        print("you think its best to wait and enjoy his company a little bit more")
        time.sleep(1.5)
        print("The more you spend time with him, the more interesting and charming he gets")
        time.sleep(1.5)
        arnold_winner()
    else:
        print("I'm sorry, I didn't recognize that. Please try again")
        time.sleep(1)
        arnold_coffee()
def arnold_winner():
    print("By the time you finish talking its very late!")
    print()
    time.sleep(1.5)
    print("Since he has been so kind and charming, you decide to close the gym with him and go for a walk along the Thames River")
    print()
    time.sleep(1.5)
    print("As the night winds along, Arnold seems to get more and more relaxed, calm and conversational")
    print()
    time.sleep(1.5)
    print("Whilst talking you suddenly realise how romantic this all is - a lovely night with a hot guy along the Thames")
    print()
    time.sleep(1.5)
    print("Its at that moment you suddenly realise that you have found the man of your dreams!")
    print("               ______$¦$¦$¦$ ____ $¦$¦$¦$    ")
    print("               ____$¦$_____$$__$$_____$¦$   ")
    print("               ___$¦$________$$________$¦$  ")
    print("                __ $¦$___________________$¦$   ")
    print("                ___$¦$__________________$¦$          ")
    print("               _(¯`.´¯)$¦$___________$¦$(¯`.´¯)      ")
    print("                (¯≻ ✦ ≺¯)$¦$_______$¦$(¯≻ ✦ ≺¯)        ")
    print("               _(_.^._)____$¦$___$¦$____ (_.^._)     ")
    print("               _____(¯`.´¯) __$¦$__ (¯`.´¯)          ")
    print("               ___ (¯≻ ✦ ≺¯) _ $_ (¯≻ ✦ ≺¯)            ")
    print("               _____(_.^._) (¯`.´¯)_(_.^._)          ")
    print("                  __________(¯≻ ✦ ≺¯)               ")
    print("                 _____(¯`.´¯) (_.^._) (¯`.´¯)            ")
    print("                 ___ (¯≻ ✦ ≺¯) ____(¯≻ ✦ ≺¯)           ")
    print("                 _____(_.^._) ______ (_.^._)     ")
    print()
    print()
    time.sleep(1.5)
    def congratulations():
        print("Congratulations! You've won disaster dates")
    congratulations()

start_game()
